# Generated by Django 3.2.5 on 2021-11-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cafe_index', models.IntegerField(default=0)),
                ('cafe_name', models.CharField(max_length=100)),
                ('cafe_info', models.CharField(max_length=1000)),
                ('cafe_number', models.CharField(max_length=300)),
                ('cafe_address', models.CharField(max_length=1000)),
            ],
        ),
    ]
