# Generated by Django 3.2.5 on 2021-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_index', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('thema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_left_time', models.IntegerField(blank=True, null=True)),
                ('user_difficulty', models.CharField(blank=True, max_length=6, null=True)),
                ('user_escape', models.FloatField(blank=True, null=True)),
                ('user_rate', models.FloatField(blank=True, null=True)),
                ('user_nickname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'review',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Thema',
            fields=[
                ('thema_index', models.AutoField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('thema_name', models.CharField(blank=True, max_length=100, null=True)),
                ('thema_limit_time', models.IntegerField(blank=True, null=True)),
                ('thema_genre', models.CharField(blank=True, max_length=60, null=True)),
                ('thema_level', models.IntegerField(blank=True, null=True)),
                ('thema_activity', models.CharField(blank=True, max_length=2, null=True)),
                ('thema_number_of_people', models.CharField(blank=True, max_length=60, null=True)),
                ('thema_info', models.CharField(blank=True, max_length=1000, null=True)),
                ('thema_picture', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'thema',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='cafe',
            options={'managed': False},
        ),
    ]
