# Generated by Django 3.2.5 on 2021-11-29 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_auto_20211120_2058'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cafe',
            table='cafe',
        ),
    ]
